---
title: Latinamerica-mamiferos
authors:
  - name: varios
    affiliation: Varias
    roles: writing
    corresponding: false
bibliography: references.bib

engine: knitr
---

## Introduction

Climate change in Latin America is

Taking the Sixth Assessment Report by the IPCC [@lee2023] as an starting point, we look into the development and forecasts of climate change for Latin America and the Caribbean. In addition to the evidence reported in the assessment, the current increase in a public perception of changes is also noted. In 2019 there were over 6000 event in 185 countries (some 7.6 million participants involved), expressing concern and urging for decisive climate actions.`{r} 2 + 2`

This chapter explore the impacts of climate change over Latin America and the Caribbean region. It is a complex natural geographic span with a complex political structure. We found it convenient to summarize some of the proposals to characterize the region. United Nations has propose the M49 standard [@standard1999] to facilitate the consolidation of national statistical data to regional levels. According to M49 standard Latin Ameria is a region formed by three subregions: Caribbean (28 islands, spanning 15 countries), Central America (8 countries), and South America (16 countries). This regions extends over 20,139,378 km<sup>2</sup> of land. This territory is a little more than 13% of world emerged land.
